/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodyLoginLoginAccessToken } from '../../models/body-login-login-access-token';
import { Token } from '../../models/token';

export interface LoginLoginAccessToken$Params {
      body: BodyLoginLoginAccessToken
}

export function loginLoginAccessToken(http: HttpClient, rootUrl: string, params: LoginLoginAccessToken$Params, context?: HttpContext): Observable<StrictHttpResponse<Token>> {
  const rb = new RequestBuilder(rootUrl, loginLoginAccessToken.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Token>;
    })
  );
}

loginLoginAccessToken.PATH = '/api/v1/login/access-token';
