/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemPublic } from '../models/item-public';
export interface ItemsPublic {
  count: number;
  data: Array<ItemPublic>;
}
