/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ItemPublic {
  created_at?: (string | null);
  description?: (string | null);
  id: string;
  owner_id: string;
  title: string;
}
