/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserPublic {
  created_at?: (string | null);
  email: string;
  full_name?: (string | null);
  id: string;
  is_active?: boolean;
  is_superuser?: boolean;
}
