/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserCreate {
  email: string;
  full_name?: (string | null);
  is_active?: boolean;
  is_superuser?: boolean;
  password: string;
}
