/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserPublic } from '../models/user-public';
export interface UsersPublic {
  count: number;
  data: Array<UserPublic>;
}
