/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserUpdate {
  email?: (string | null);
  full_name?: (string | null);
  is_active?: (boolean | null);
  is_superuser?: (boolean | null);
  password?: (string | null);
}
