/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserPublic } from '../../models/user-public';
import { UserUpdate } from '../../models/user-update';

export interface UsersUpdateUser$Params {
  user_id: string;
      body: UserUpdate
}

export function usersUpdateUser(http: HttpClient, rootUrl: string, params: UsersUpdateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPublic>> {
  const rb = new RequestBuilder(rootUrl, usersUpdateUser.PATH, 'patch');
  if (params) {
    rb.path('user_id', params.user_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserPublic>;
    })
  );
}

usersUpdateUser.PATH = '/api/v1/users/{user_id}';
