/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserPublic } from '../../models/user-public';
import { UserUpdateMe } from '../../models/user-update-me';

export interface UsersUpdateUserMe$Params {
      body: UserUpdateMe
}

export function usersUpdateUserMe(http: HttpClient, rootUrl: string, params: UsersUpdateUserMe$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPublic>> {
  const rb = new RequestBuilder(rootUrl, usersUpdateUserMe.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserPublic>;
    })
  );
}

usersUpdateUserMe.PATH = '/api/v1/users/me';
