/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemPublic } from '../../models/item-public';
import { ItemUpdate } from '../../models/item-update';

export interface ItemsUpdateItem$Params {
  id: string;
      body: ItemUpdate
}

export function itemsUpdateItem(http: HttpClient, rootUrl: string, params: ItemsUpdateItem$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemPublic>> {
  const rb = new RequestBuilder(rootUrl, itemsUpdateItem.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItemPublic>;
    })
  );
}

itemsUpdateItem.PATH = '/api/v1/items/{id}';
