/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemPublic } from '../../models/item-public';

export interface ItemsReadItem$Params {
  id: string;
}

export function itemsReadItem(http: HttpClient, rootUrl: string, params: ItemsReadItem$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemPublic>> {
  const rb = new RequestBuilder(rootUrl, itemsReadItem.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItemPublic>;
    })
  );
}

itemsReadItem.PATH = '/api/v1/items/{id}';
