/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrivateUserCreate } from '../../models/private-user-create';
import { UserPublic } from '../../models/user-public';

export interface PrivateCreateUser$Params {
      body: PrivateUserCreate
}

export function privateCreateUser(http: HttpClient, rootUrl: string, params: PrivateCreateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPublic>> {
  const rb = new RequestBuilder(rootUrl, privateCreateUser.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserPublic>;
    })
  );
}

privateCreateUser.PATH = '/api/v1/private/users/';
